### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by nothing2048** [embedthis/esp-vue-skeleton#1]
when I install
it tips
  [Info] Search catalog: "internal" for esp-vue-skeleton for version ~*
      [Info] Search catalog: "bower" for esp-vue-skeleton for version ~*
      [Info] Search catalog: "npm" for esp-vue-skeleton for version ~*
      [Info] Search catalog: "github" for esp-vue-skeleton for version ~*
ReferenceError Exception: Missing property OWNER
Stack:
 [00] src/pak.es, line 2335, locatePak, cmd = cmd.expand({NAME: pak.name})
 [01] src/pak.es, line 1219, installCommon, locatePak(pak)
 [02] src/pak.es, line 1194, install, installCommon(Package(name, version))
 [03] src/pak.es, line 700, process, install(rest)
 [04] src/pak.es, line 526, main, process()
 [05] src/pak.es, line 2881, __initializer__, } /* ejs.pak module */

      [Warn] Cannot access catalog at: https://api.github.com/repos/${OWNER}/${NAME}
pak: ERROR: Cannot continue with offline primary catalog https://api.github.com/repos/${OWNER}/${NAME}
Wait or retry with --force

**Comment by dev-embedthis** [comment]
Thanks for the report. Working on this now.

The esp-vue-skeleton will need to qualify its dependencies and when we've fixed that, you will need to install as:

```
pak install embedthis/esp-vue-skeleton
```

However that wont work until we make the fix to the skeleton.

We'll update the doc to match.

**Comment by dev-embedthis** [comment]
Should be fixed now.

You will need to update pak to version 1.0.4 and then try to install again:

```
pak -i install embedthis/esp-vue-skeleton
```
